[package]
name = "gltf_ktxer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.28"
# gltf = { version = "1.4.1", features = ["extensions", "extras", "names"] }
thiserror = "2.0.11"
serde_json = "1.0.138"
serde = "1.0.217"
base64 = "0.22.1"
serde_derive = "1.0.217"
image = "0.25.5"
